# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Enes Tasbasi
tagline:             Blog
description:         
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Enes Tasbasi
  url:               https://github.com/etasbasi
  email:             enestasbasi

# Custom vars
version:             1.0.0
