
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://etasbasi.github.io"

# If you're hosting your site at a Projec t repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Enes Tasbasi"
title: "{ Enes Tasbasi }"
description: "This is a personal website of Enes Tasbasi"
keywords: "technology"
favicon: "/img/favicon.ico"

################
# Header layout #
################

# black-favicon: "/img/india.jpg"

background-img: "../img/istanbul.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Live as if you were to die tomorrow; learn as if you were to live forever."

me-img: "/img/IMG_0503.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: false
fb-share: true
twitter-share: true
linkedin-share: false
reddit-share: false
google-plus-share: false
tumblr-share: false
pinterest-share: false
pocket-share: false
vkontakte-share: false

disqus-shortname: "etasbasi"

syntax-highlight: True

############
# Timeline #
############


events:
  - image: "/img/timeline/black.jpg"
    date: "2015"
    description: "Started programming :smirk:"
  - image: "/img/timeline/black.jpg"
    date: "2014"
    description: "Came to the United States."
  - image: "/img/timeline/black.jpg"
    date: "January 13, 2000"
    description: "Born in Istanbul, Turkey"


 # First image of the Timeline

timeline-img: "/img/timeline/black.jpg"

###########
# Contact #
###########

email: "etasbasi@outlook.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Enes Tasbasi is a software developer who was born in Turkey, and currently lives in the United States."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/EnesTasbasi1876"
  - title: "twitter"
    url: "https://twitter.com/EnesTasbasi1"
  - title: "github"
    url: "https://github.com/etasbasi"
  # - title: "bitcoin"
  #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  # - title: "rss"
  #   url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
